//! 数据权限 PG 表结构 DDL（幂等）。
//!
//! 硬约束（对齐 rule/flow store-pg）：`cmx_dataauth_` 前缀；禁外键，用索引替代；DDL 幂等
//! （IF NOT EXISTS）。多租户（db-per-tenant）：表内不带 tenant 列（库即租户边界）。
//! 六表：策略 / 授权 / 关系元组 / 层级维度值 / 列脱敏规则 / 审计。

/// 建表 DDL（幂等）。按顺序执行。
pub const DDL_STATEMENTS: &[&str] = &[
    // —— 策略（约束 AST 模板 + 效果）——
    r#"CREATE TABLE IF NOT EXISTS cmx_dataauth_policy (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name            VARCHAR(256) NOT NULL DEFAULT '',
        resource_kind   VARCHAR(128) NOT NULL,
        action          VARCHAR(32)  NOT NULL DEFAULT 'read',
        source          VARCHAR(32)  NOT NULL DEFAULT 'inline',
        constraint_json JSONB        NOT NULL,
        priority        INTEGER      NOT NULL DEFAULT 0,
        effect          VARCHAR(16)  NOT NULL DEFAULT 'permit',
        enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
        created_at      TIMESTAMPTZ  NOT NULL,
        updated_at      TIMESTAMPTZ  NOT NULL
    )"#,
    // 补列（老库平滑升级）。
    "ALTER TABLE cmx_dataauth_policy ADD COLUMN IF NOT EXISTS source VARCHAR(32) NOT NULL DEFAULT 'inline'",
    "ALTER TABLE cmx_dataauth_policy ADD COLUMN IF NOT EXISTS valid_from TIMESTAMPTZ",
    "ALTER TABLE cmx_dataauth_policy ADD COLUMN IF NOT EXISTS valid_to TIMESTAMPTZ",
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_policy_lookup ON cmx_dataauth_policy (resource_kind, action)",
    // —— 授权：策略 ↔ 主体 + 维度值集 ——
    r#"CREATE TABLE IF NOT EXISTS cmx_dataauth_grant (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        policy_id    BIGINT       NOT NULL,
        subject_type VARCHAR(32)  NOT NULL,
        subject_id   VARCHAR(128) NOT NULL,
        dim_key      VARCHAR(128),
        dim_values   JSONB        NOT NULL DEFAULT '[]',
        inherit      BOOLEAN      NOT NULL DEFAULT TRUE,
        created_at   TIMESTAMPTZ  NOT NULL,
        updated_at   TIMESTAMPTZ  NOT NULL
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_grant_subject ON cmx_dataauth_grant (subject_type, subject_id)",
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_grant_policy ON cmx_dataauth_grant (policy_id)",
    "ALTER TABLE cmx_dataauth_grant ADD COLUMN IF NOT EXISTS valid_from TIMESTAMPTZ",
    "ALTER TABLE cmx_dataauth_grant ADD COLUMN IF NOT EXISTS valid_to TIMESTAMPTZ",
    // —— ReBAC 关系元组 ——
    r#"CREATE TABLE IF NOT EXISTS cmx_dataauth_relation_tuple (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        object_kind  VARCHAR(128) NOT NULL,
        object_id    VARCHAR(128) NOT NULL,
        relation     VARCHAR(64)  NOT NULL,
        subject_kind VARCHAR(64)  NOT NULL,
        subject_id   VARCHAR(128) NOT NULL,
        created_at   TIMESTAMPTZ  NOT NULL
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_tuple_lookup ON cmx_dataauth_relation_tuple (object_kind, relation, subject_kind, subject_id)",
    // —— 层级维度值（descendants 展开数据源）——
    r#"CREATE TABLE IF NOT EXISTS cmx_dataauth_dimension_value (
        dim_key      VARCHAR(128) NOT NULL,
        dim_value    VARCHAR(128) NOT NULL,
        parent_value VARCHAR(128),
        label        VARCHAR(256),
        depth        INTEGER      NOT NULL DEFAULT 0,
        PRIMARY KEY (dim_key, dim_value)
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_dimval_parent ON cmx_dataauth_dimension_value (dim_key, parent_value)",
    // —— 列脱敏规则（column_name 避 SQL 保留字 column）——
    r#"CREATE TABLE IF NOT EXISTS cmx_dataauth_mask_rule (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        resource_kind   VARCHAR(128) NOT NULL,
        column_name     VARCHAR(128) NOT NULL,
        mask_type       VARCHAR(16)  NOT NULL,
        partial_pattern VARCHAR(128),
        condition_expr  TEXT,
        min_role        VARCHAR(128),
        created_at      TIMESTAMPTZ  NOT NULL,
        updated_at      TIMESTAMPTZ  NOT NULL
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_mask_kind ON cmx_dataauth_mask_rule (resource_kind)",
    // —— 决策审计 ——
    r#"CREATE TABLE IF NOT EXISTS cmx_dataauth_audit_log (
        id              VARCHAR(64)  PRIMARY KEY,
        user_id         VARCHAR(128) NOT NULL,
        resource_kind   VARCHAR(128) NOT NULL,
        action          VARCHAR(32)  NOT NULL,
        effect          VARCHAR(16)  NOT NULL,
        constraint_json JSONB        NOT NULL,
        backend         VARCHAR(32),
        created_at      TIMESTAMPTZ  NOT NULL
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_audit_created ON cmx_dataauth_audit_log (created_at)",
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_audit_user ON cmx_dataauth_audit_log (user_id)",
    // 审计上下文补列（老库平滑升级）。
    "ALTER TABLE cmx_dataauth_audit_log ADD COLUMN IF NOT EXISTS subject_ctx JSONB",
    "ALTER TABLE cmx_dataauth_audit_log ADD COLUMN IF NOT EXISTS obligations JSONB",
    // effect 存 DecisionEffect（permitWithConstraint 达 21 字符）→ 原 VARCHAR(16) 溢出，加宽。
    "ALTER TABLE cmx_dataauth_audit_log ALTER COLUMN effect TYPE VARCHAR(32)",
    // —— 配置变更审计（谁改了哪条配置）——
    r#"CREATE TABLE IF NOT EXISTS cmx_dataauth_change_log (
        id            VARCHAR(64)  PRIMARY KEY,
        actor         VARCHAR(128) NOT NULL DEFAULT '',
        op            VARCHAR(16)  NOT NULL,
        entity_type   VARCHAR(64)  NOT NULL,
        entity_id     VARCHAR(128) NOT NULL DEFAULT '',
        detail        JSONB,
        created_at    TIMESTAMPTZ  NOT NULL
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_change_created ON cmx_dataauth_change_log (created_at)",
    "CREATE INDEX IF NOT EXISTS idx_cmx_dataauth_change_entity ON cmx_dataauth_change_log (entity_type, entity_id)",
];
